version: '3.8'

# Development overrides for docker-compose.yml
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  postgres:
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: sop_rag_dev

  backend:
    environment:
      DEBUG: "True"
      DATABASE_URL: postgresql://dev_user:dev_password@postgres:5432/sop_rag_dev
      SQLALCHEMY_ECHO: "True"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  celery_worker:
    environment:
      DEBUG: "True"
      DATABASE_URL: postgresql://dev_user:dev_password@postgres:5432/sop_rag_dev
    command: celery -A app.tasks.celery_app worker --loglevel=debug

  frontend:
    environment:
      REACT_APP_API_URL: http://localhost:8000/api/v1
      REACT_APP_WS_URL: ws://localhost:8000/ws
    command: npm run dev
    ports:
      - "3000:3000"
